### ISSUE TITLE
Not working with newly created records

### ISSUE THREAD

**Issue by maicol07** [kissgyorgy/cloudflare-dyndns#6]
It seems that records deleted and then recreated with the same name are not working with cloudflare-dyndns:

![](https://user-images.githubusercontent.com/9463142/115271266-700e6280-a13d-11eb-8a19-8319cf51b041.png)

**Comment by maicol07** [comment]
How can I check if the cached zone record exists? Do I have to check in the cache file?

**Comment by maicol07** [comment]
How can I check if the cached zone record exists? Do I have to check in the cache file?

**Comment by kissgyorgy** [comment]
It's not really important to check the cache file, it's only for making things faster and not having to hit the Cloudflare API when IP didn't change, but you can delete it any time, and it will set the records, no problem.

I never noticed the typo, thanks! 😄

**Comment by kissgyorgy** [comment]
> How can I check if the cached zone record exists? Do I have to check in the cache file?

Oh, we misunderstood each other, for you, the only thing to do is to delete the cache file and run the script again.

For me, it's to catch this error and handle it in code.

**Comment by kissgyorgy** [comment]
Hey, I was thinking about this, and you are not supposed to  change manually and use dyndns at the same time, because that will lead all kinds of conflicts and problems like this. You either should give it exclusive access, or update the records manually.

I'm thinking about changing the error message or just a warning about this in the README.
I don't really want to overwrite manually created records without notice.

What's your use-case?

**Comment by maicol07** [comment]
No use-case. That was only a test. I had changed manually the record to test a CDN service. Then I've switched back to the original one

**Comment by kissgyorgy** [comment]
Thanks, I will definitely document this, not sure about the proper fix.
